SOURCES = [
    {
        "name": "The Blueprint",
        "url": "https://theblueprint.ru/news",
        "section": "events",
        "category": "Fashion / Art / Culture",
        "region": "russia",
        "description": "Российское медиа о моде, культуре, искусстве, индустрии и актуальных событиях.",
        "include": ["/news", "/fashion", "/culture", "/art"],
        "limit": 6,
    },
    {
        "name": "BURO.",
        "url": "https://www.buro247.ru/fashion",
        "section": "events",
        "category": "Fashion / Culture",
        "region": "russia",
        "description": "Медиа о моде, культуре, искусстве, lifestyle и городских событиях.",
        "include": ["/fashion", "/culture", "/lifestyle", "/news"],
        "limit": 6,
    },
    {
        "name": "Design Mate",
        "url": "https://design-mate.ru/contest",
        "section": "calls",
        "category": "Design / Architecture",
        "region": "russia",
        "description": "Ресурс про дизайн, архитектуру, интерьер, предметную среду и конкурсы.",
        "include": ["/contest", "/competition", "/events"],
        "limit": 6,
    },
    {
        "name": "Артгид",
        "url": "https://artguide.com/practices",
        "fallback_urls": ["https://artguide.com/events", "https://artguide.com/news", "https://artguide.com/articles"],
        "section": "events",
        "category": "Art / Exhibitions / Open Calls",
        "region": "russia",
        "description": "Медиа о современном искусстве, музеях, галереях, выставках, грантах и резиденциях.",
        "include": ["/events", "/news", "/articles", "/practices"],
        "limit": 6,
    },
    {
        "name": "ART Узел",
        "url": "https://artuzel.com/competitions",
        "section": "calls",
        "category": "Open Calls / Art / Residencies",
        "region": "russia",
        "description": "Независимый медиа-проект о современном искусстве, конкурсах, грантах и резиденциях.",
        "include": ["/competitions", "/residencies", "/grants", "/open-call"],
        "limit": 6,
    },
    {
        "name": "Vogue Business",
        "url": "https://www.vogue.com/business/fashion",
        "section": "world",
        "category": "Fashion Business",
        "region": "world",
        "description": "Международное медиа о fashion-индустрии, брендах, luxury, технологиях и fashion week.",
        "include": ["/article", "/fashion", "/business"],
        "limit": 6,
    },
    {
        "name": "Dezeen",
        "url": "https://www.dezeen.com/design/",
        "feed_url": "https://www.dezeen.com/design/feed/",
        "section": "world",
        "category": "Design / Architecture",
        "region": "world",
        "description": "Мировое медиа про дизайн, архитектуру, интерьеры и предметную среду.",
        "include": ["/design", "/architecture", "/interiors"],
        "limit": 6,
    },
    {
        "name": "designboom",
        "url": "https://www.designboom.com/",
        "feed_url": "https://www.designboom.com/feed/",
        "section": "world",
        "category": "Design / Art / Technology",
        "region": "world",
        "description": "Международное медиа о дизайне, архитектуре, искусстве и креативных технологиях.",
        "include": ["/design/", "/art/", "/architecture/", "/technology/"],
        "limit": 6,
    },
    {
        "name": "e-flux",
        "url": "https://www.e-flux.com/announcements",
        "section": "calls",
        "category": "Contemporary Art",
        "region": "world",
        "description": "Международный источник объявлений о contemporary art, выставках, институциях и open calls.",
        "include": ["/announcements", "/open-call", "/program"],
        "limit": 6,
    },
    {
        "name": "ArtConnect",
        "url": "https://www.artconnect.com/opportunities",
        "section": "calls",
        "category": "Open Calls / Residencies / Grants",
        "region": "world",
        "description": "Агрегатор возможностей для художников: open calls, резиденции, гранты и awards.",
        "include": ["/opportunity", "/opportunities"],
        "limit": 6,
    },
]
